server: 
    port: 8087
    
spring: 
    jpa: 
        hibernate: 
            ddl-auto: none
    datasource: 
        url: jdbc:mysql://localhost:3306/our_spring_boot_app
        username: root
        password: root
        driverClassName: com.mysql.cj.jdbc.Driver